name: 'Phillip Henault'
description: 'This action allows publishing html summaries'
author: 'Baker Hughes'
inputs:
  path: 
    required: true
    description: 'The path to the html file.'
  heading: 
    required: true
    description: 'The heading of the summary.'
runs:
  using: 'node16'
  main: 'dist/index.js'
